project:
  name: {{cookiecutter.project_name}}
  repo_name: {{cookiecutter.repo_name}}
  repo_name: {{cookiecutter.repo_name}}
  aws_connector: {{cookiecutter.aws_connector}}
defaults:
  installs:
    - pyyaml
    - pytest-venv
    - mkdocs
    - mkdocs-cinder
    - cookiecutter
    - pytest
    - poetry
    - poetry-lock-package
    - tox
    - click # external requirements
    - Sphinx
    - coverage
    - awscli
    - flake8
    - boto3
    - python-dotenv>=0.5.1
  {{% if cookiecutter.python_interpreter != 'python3' %}}
    - pathlib2 # backwards compatibility
  {{% endif %}}